# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sql


class Ui_UserWindow(QtWidgets.QMainWindow):
    def reload(self):
        """重新读取用户"""
        userdb = sql.getuser()
        i = 0
        self.tbUser.setRowCount(len(userdb.keys()))
        for ur, pwd in userdb.items():
            print(ur, pwd)
            self.tbUser.setItem(i, 0, QtWidgets.QTableWidgetItem(str(ur)))
            self.tbUser.setItem(i, 1, QtWidgets.QTableWidgetItem(str(pwd)))
            i += 1
        self.tbUser.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    def DELETE(self):
        user = self.tbUser.item(self.tbUser.currentRow(), 0).text()
        confirm = QtWidgets.QMessageBox.question(self, "提示", f"是否要删除用户 {user} ？")
        if confirm == QtWidgets.QMessageBox.Yes:
            flag = sql.delteuser(user)
            if flag:
                QtWidgets.QMessageBox.information(self, "提示", "删除用户成功！")
                self.reload()
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "删除失败！")
    def ADD(self):
        """插入用户"""
        if self.editName.text() == "" or self.editPwd.text() == "":
            QtWidgets.QMessageBox.warning(self, "提示", "请输入正确的用户名和密码名！")
        else:
            flag = sql.adduser(self.editName.text(), self.editPwd.text())
            if flag:
                QtWidgets.QMessageBox.information(self, "提示", "新用户增加成功！")
                self.reload()
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "增加失败！")
    def EDIT(self):
        if self.tbUser.currentColumn() == 0:
            text, flag = QtWidgets.QInputDialog.getText(self, "修改用户名", "请输入修改之后的用户名：", QtWidgets.QLineEdit.Normal, self.tbUser.currentItem().text())
            if flag and text != "":
                sqlflag = sql.edituser(0, text, self.tbUser.item(self.tbUser.currentRow(), 1).text())
                if sqlflag:
                    QtWidgets.QMessageBox.information(self, "提示", "修改成功！")
                    self.reload()
                else:
                    QtWidgets.QMessageBox.critical(self, "提示", "修改失败！非法输入！")
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "修改失败！请输入非空字符串！")
        elif self.tbUser.currentColumn() == 1:
            text, flag = QtWidgets.QInputDialog.getText(self, "修改密码", "请输入修改之后的密码：", QtWidgets.QLineEdit.PasswordEchoOnEdit, self.tbUser.currentItem().text())
            if flag and text != "":
                sqlflag = sql.edituser(1, int(self.tbUser.item(self.tbUser.currentRow(), 0).text()), text)
                if sqlflag:
                    QtWidgets.QMessageBox.information(self, "提示", "修改成功！")
                    self.reload()
                else:
                    QtWidgets.QMessageBox.critical(self, "提示", "修改失败！非法输入！")
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "修改失败！请输入非空字符串！")
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(283, 240)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/images/appstu.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbUser = QtWidgets.QTableWidget(self.centralwidget)
        self.tbUser.setGeometry(QtCore.QRect(0, 0, 281, 161))
        self.tbUser.setObjectName("tbUser")
        self.tbUser.setColumnCount(2)
        self.tbUser.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbUser.setHorizontalHeaderItem(1, item)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(148, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setGeometry(QtCore.QRect(77, 170, 61, 20))
        self.editName.setObjectName("editName")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(4, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.editPwd = QtWidgets.QLineEdit(self.centralwidget)
        self.editPwd.setGeometry(QtCore.QRect(218, 170, 61, 20))
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPwd.setObjectName("editPwd")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(47, 201, 51, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(107, 201, 51, 31))
        self.btnEdit.setObjectName("btnEdit")
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setGeometry(QtCore.QRect(167, 201, 51, 31))
        self.btnDel.setObjectName("btnDel")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(227, 201, 51, 31))
        self.btnExit.setObjectName("btnExit")
        UserWindow.setCentralWidget(self.centralwidget)
        self.reload()

        self.retranslateUi(UserWindow)
        self.btnExit.clicked.connect(UserWindow.close)
        self.btnAdd.clicked.connect(self.ADD)
        self.btnDel.clicked.connect(self.DELETE)
        self.btnEdit.clicked.connect(self.EDIT)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "用户信息维护"))
        item = self.tbUser.horizontalHeaderItem(0)
        item.setText(_translate("UserWindow", "用户名"))
        item = self.tbUser.horizontalHeaderItem(1)
        item.setText(_translate("UserWindow", "密码"))
        self.label_3.setText(_translate("UserWindow", "用户密码："))
        self.label_2.setText(_translate("UserWindow", "用户名称："))
        self.btnAdd.setText(_translate("UserWindow", "添加"))
        self.btnEdit.setText(_translate("UserWindow", "修改"))
        self.btnDel.setText(_translate("UserWindow", "删除"))
        self.btnExit.setText(_translate("UserWindow", "退出"))

import rc_rc
