# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sql


class Ui_resultinfoWindow(QtWidgets.QMainWindow):
    def reload(self):
        for i in range(self.tbResult.rowCount()):
            # 先全部显示
            self.tbResult.showRow(i)
        for i in range(self.tbResult.rowCount()):
            if self.cboxSubject.currentText() != "所有":
                if self.tbResult.item(i, 4).text() != self.cboxSubject.currentText():
                    self.tbResult.hideRow(i)
            if self.cboxKinds.currentText() != "所有":
                if self.tbResult.item(i, 3).text() != self.cboxKinds.currentText():
                    self.tbResult.hideRow(i)
            if self.editName.text() != "":
                if self.editName.text() not in self.tbResult.item(i, 1).text():
                    self.tbResult.hideRow(i)
    def initialization(self):
        print("INITIALIZING")
        self.result = sql.result()
        self.cboxKinds.addItems(self.result.examkindsdict.values())
        self.cboxSubject.addItems(self.result.subjectdict.values())
        self.cboxKinds.addItem("所有")
        self.cboxSubject.addItem("所有")
        self.cboxKinds.setCurrentIndex(len(self.result.examkindsdict))
        self.cboxSubject.setCurrentIndex(len(self.result.subjectdict))
        self.resultdb = self.result.getresult()
        self.tbResult.setRowCount(len(self.resultdb))
        for i in range(self.tbResult.rowCount()):
            self.tbResult.setItem(i, 0, QtWidgets.QTableWidgetItem(str(self.resultdb[i][1])))
            self.tbResult.setItem(i, 1, QtWidgets.QTableWidgetItem(self.result.studentdict[self.resultdb[i][1]]))
            self.tbResult.setItem(i, 2, QtWidgets.QTableWidgetItem(self.result.classdict[self.result.stuclassdict[self.resultdb[i][1]]]))
            self.tbResult.setItem(i, 3, QtWidgets.QTableWidgetItem(self.result.examkindsdict[self.resultdb[i][2]]))
            self.tbResult.setItem(i, 4, QtWidgets.QTableWidgetItem(self.result.subjectdict[self.resultdb[i][3]]))
            self.tbResult.setItem(i, 5, QtWidgets.QTableWidgetItem(str(self.resultdb[i][4])))
        self.tbResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    def setupUi(self, resultinfoWindow):
        resultinfoWindow.setObjectName("resultinfoWindow")
        resultinfoWindow.resize(762, 343)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/images/appstu.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        resultinfoWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(resultinfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(327, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cboxKinds = QtWidgets.QComboBox(self.centralwidget)
        self.cboxKinds.setGeometry(QtCore.QRect(400, 10, 69, 22))
        self.cboxKinds.setObjectName("cboxKinds")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(709, 3, 51, 31))
        self.btnExit.setObjectName("btnExit")
        self.btnQuery = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuery.setGeometry(QtCore.QRect(649, 3, 51, 31))
        self.btnQuery.setObjectName("btnQuery")
        self.tbResult = QtWidgets.QTableWidget(self.centralwidget)
        self.tbResult.setGeometry(QtCore.QRect(0, 40, 761, 301))
        self.tbResult.setObjectName("tbResult")
        self.tbResult.setColumnCount(6)
        self.tbResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbResult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbResult.setHorizontalHeaderItem(5, item)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cboxSubject = QtWidgets.QComboBox(self.centralwidget)
        self.cboxSubject.setGeometry(QtCore.QRect(557, 9, 69, 22))
        self.cboxSubject.setObjectName("cboxSubject")
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setGeometry(QtCore.QRect(224, 10, 91, 20))
        self.editName.setObjectName("editName")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        resultinfoWindow.setCentralWidget(self.centralwidget)
        self.initialization()

        self.retranslateUi(resultinfoWindow)
        self.btnExit.clicked.connect(resultinfoWindow.close)
        self.btnQuery.clicked.connect(self.reload)
        self.cboxSubject.currentIndexChanged.connect(self.reload)
        self.cboxKinds.currentIndexChanged.connect(self.reload)
        self.editName.returnPressed.connect(self.reload)
        QtCore.QMetaObject.connectSlotsByName(resultinfoWindow)

    def retranslateUi(self, resultinfoWindow):
        _translate = QtCore.QCoreApplication.translate
        resultinfoWindow.setWindowTitle(_translate("resultinfoWindow", "学生成绩查询"))
        self.label_2.setText(_translate("resultinfoWindow", "考试种类："))
        self.btnExit.setText(_translate("resultinfoWindow", "退出"))
        self.btnQuery.setText(_translate("resultinfoWindow", "查询"))
        item = self.tbResult.horizontalHeaderItem(0)
        item.setText(_translate("resultinfoWindow", "学生编号"))
        item = self.tbResult.horizontalHeaderItem(1)
        item.setText(_translate("resultinfoWindow", "学生姓名"))
        item = self.tbResult.horizontalHeaderItem(2)
        item.setText(_translate("resultinfoWindow", "班级"))
        item = self.tbResult.horizontalHeaderItem(3)
        item.setText(_translate("resultinfoWindow", "种类"))
        item = self.tbResult.horizontalHeaderItem(4)
        item.setText(_translate("resultinfoWindow", "科目"))
        item = self.tbResult.horizontalHeaderItem(5)
        item.setText(_translate("resultinfoWindow", "成绩"))
        self.label_5.setText(_translate("resultinfoWindow", "考试科目："))
        self.label_7.setText(_translate("resultinfoWindow", "输入学生姓名："))
import rc_rc
