# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'examkinds.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sql


class Ui_examkinds(QtWidgets.QMainWindow):
    def reload(self):
        """重新读取"""
        db = sql.getexamkinds()
        i = 0
        self.tbKinds.setRowCount(len(db.keys()))
        for id, gd in db.items():
            print(id, gd)
            self.tbKinds.setItem(i, 0, QtWidgets.QTableWidgetItem(str(id)))
            self.tbKinds.setItem(i, 1, QtWidgets.QTableWidgetItem(str(gd)))
            i += 1
        self.tbKinds.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    def DELETE(self):
        if self.tbKinds.currentRow() == -1:
            QtWidgets.QMessageBox.warning(self, "提示", "没有选择要删除的项目！")
            return None
        id = self.tbKinds.item(self.tbKinds.currentRow(), 0).text()
        confirm = QtWidgets.QMessageBox.question(self, "提示", f"是否要删除类型ID {id} ？")
        if confirm == QtWidgets.QMessageBox.Yes:
            flag = sql.delteexamkinds(id)
            if flag:
                QtWidgets.QMessageBox.information(self, "提示", "删除类型成功！")
                self.reload()
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "删除失败！")
    def ADD(self):
        """插入科目"""
        if self.editID.text() == "" or self.editName.text() == "":
            QtWidgets.QMessageBox.warning(self, "提示", "请输入正确的ID和名称！")
        else:
            flag = sql.addexamkinds(self.editID.text(), self.editName.text())
            if flag:
                QtWidgets.QMessageBox.information(self, "提示", "新类型增加成功！")
                self.reload()
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "增加失败！")
    def EDIT(self):
        if self.tbKinds.currentColumn() == 0:
            text, flag = QtWidgets.QInputDialog.getInt(self, "修改ID", "请输入修改后的ID：", int(self.tbKinds.currentItem().text()), 0, 100, 1)
            if flag and text != "":
                sqlflag = sql.editexamkinds(0, text, self.tbKinds.item(self.tbKinds.currentRow(), 1).text())
                if sqlflag:
                    QtWidgets.QMessageBox.information(self, "提示", "修改成功！")
                    self.reload()
                else:
                    QtWidgets.QMessageBox.critical(self, "提示", "修改失败！非法输入！")
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "修改失败！请输入非空字符串！")
        elif self.tbKinds.currentColumn() == 1:
            text, flag = QtWidgets.QInputDialog.getText(self, "修改名称", "请输入修改之后的名称：", QtWidgets.QLineEdit.Normal, self.tbKinds.currentItem().text())
            if flag and text != "":
                sqlflag = sql.editexamkinds(1, self.tbKinds.item(self.tbKinds.currentRow(), 0).text(), text)
                if sqlflag:
                    QtWidgets.QMessageBox.information(self, "提示", "修改成功！")
                    self.reload()
                else:
                    QtWidgets.QMessageBox.critical(self, "提示", "修改失败！非法输入！")
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "修改失败！请输入非空字符串！")

    def setupUi(self, examkinds):
        examkinds.setObjectName("examkinds")
        examkinds.resize(286, 237)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/images/appstu.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        examkinds.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(examkinds)
        self.centralwidget.setObjectName("centralwidget")
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setGeometry(QtCore.QRect(221, 170, 61, 20))
        self.editName.setObjectName("editName")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(230, 201, 51, 31))
        self.btnExit.setObjectName("btnExit")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(110, 201, 51, 31))
        self.btnEdit.setObjectName("btnEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(151, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(7, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(50, 201, 51, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setGeometry(QtCore.QRect(170, 201, 51, 31))
        self.btnDel.setObjectName("btnDel")
        self.tbKinds = QtWidgets.QTableWidget(self.centralwidget)
        self.tbKinds.setGeometry(QtCore.QRect(3, 0, 281, 161))
        self.tbKinds.setObjectName("tbKinds")
        self.tbKinds.setColumnCount(2)
        self.tbKinds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbKinds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbKinds.setHorizontalHeaderItem(1, item)
        self.editID = QtWidgets.QLineEdit(self.centralwidget)
        self.editID.setGeometry(QtCore.QRect(80, 170, 61, 20))
        self.editID.setObjectName("editID")
        examkinds.setCentralWidget(self.centralwidget)
        self.reload()

        self.retranslateUi(examkinds)
        self.btnExit.clicked.connect(examkinds.close)
        self.btnDel.clicked.connect(self.DELETE)
        self.btnAdd.clicked.connect(self.ADD)
        self.btnEdit.clicked.connect(self.EDIT)
        QtCore.QMetaObject.connectSlotsByName(examkinds)

    def retranslateUi(self, examkinds):
        _translate = QtCore.QCoreApplication.translate
        examkinds.setWindowTitle(_translate("examkinds", "考试类别设置"))
        self.btnExit.setText(_translate("examkinds", "退出"))
        self.btnEdit.setText(_translate("examkinds", "修改"))
        self.label_3.setText(_translate("examkinds", "类别名称："))
        self.label_2.setText(_translate("examkinds", "类别编号："))
        self.btnAdd.setText(_translate("examkinds", "添加"))
        self.btnDel.setText(_translate("examkinds", "删除"))
        item = self.tbKinds.horizontalHeaderItem(0)
        item.setText(_translate("examkinds", "类别编号"))
        item = self.tbKinds.horizontalHeaderItem(1)
        item.setText(_translate("examkinds", "类别名称"))
import rc_rc
