# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subject.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sql

class Ui_subject(QtWidgets.QMainWindow):
    def reload(self):
        """重新读取"""
        db = sql.getsubject()
        i = 0
        self.tbSubject.setRowCount(len(db.keys()))
        for id, gd in db.items():
            print(id, gd)
            self.tbSubject.setItem(i, 0, QtWidgets.QTableWidgetItem(str(id)))
            self.tbSubject.setItem(i, 1, QtWidgets.QTableWidgetItem(str(gd)))
            i += 1
        self.tbSubject.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    def DELETE(self):
        if self.tbSubject.currentRow() == -1:
            QtWidgets.QMessageBox.warning(self, "提示", "没有选择要删除的项目！")
            return None
        id = self.tbSubject.item(self.tbSubject.currentRow(), 0).text()
        confirm = QtWidgets.QMessageBox.question(self, "提示", f"是否要删除科目ID {id} ？")
        if confirm == QtWidgets.QMessageBox.Yes:
            flag = sql.deltesubject(id)
            if flag:
                QtWidgets.QMessageBox.information(self, "提示", "删除科目成功！")
                self.reload()
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "删除失败！")
    def ADD(self):
        """插入科目"""
        if self.editID.text() == "" or self.editName.text() == "":
            QtWidgets.QMessageBox.warning(self, "提示", "请输入正确的ID和名称！")
        else:
            flag = sql.addsubject(self.editID.text(), self.editName.text())
            if flag:
                QtWidgets.QMessageBox.information(self, "提示", "新科目增加成功！")
                self.reload()
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "增加失败！")
    def EDIT(self):
        if self.tbSubject.currentColumn() == 0:
            text, flag = QtWidgets.QInputDialog.getInt(self, "修改ID", "请输入修改后的ID：", int(self.tbSubject.currentItem().text()), 0, 100, 1)
            if flag and text != "":
                sqlflag = sql.editsubject(0, text, self.tbSubject.item(self.tbSubject.currentRow(), 1).text())
                if sqlflag:
                    QtWidgets.QMessageBox.information(self, "提示", "修改成功！")
                    self.reload()
                else:
                    QtWidgets.QMessageBox.critical(self, "提示", "修改失败！非法输入！")
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "修改失败！请输入非空字符串！")
        elif self.tbSubject.currentColumn() == 1:
            text, flag = QtWidgets.QInputDialog.getText(self, "修改名称", "请输入修改之后的名称：", QtWidgets.QLineEdit.Normal, self.tbSubject.currentItem().text())
            if flag and text != "":
                sqlflag = sql.editsubject(1, self.tbSubject.item(self.tbSubject.currentRow(), 0).text(), text)
                if sqlflag:
                    QtWidgets.QMessageBox.information(self, "提示", "修改成功！")
                    self.reload()
                else:
                    QtWidgets.QMessageBox.critical(self, "提示", "修改失败！非法输入！")
            else:
                QtWidgets.QMessageBox.critical(self, "提示", "修改失败！请输入非空字符串！")

    def setupUi(self, subject):
        subject.setObjectName("subject")
        subject.resize(283, 240)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/images/appstu.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        subject.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(subject)
        self.centralwidget.setObjectName("centralwidget")
        self.tbSubject = QtWidgets.QTableWidget(self.centralwidget)
        self.tbSubject.setGeometry(QtCore.QRect(0, 0, 281, 161))
        self.tbSubject.setObjectName("tbSubject")
        self.tbSubject.setColumnCount(2)
        self.tbSubject.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbSubject.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbSubject.setHorizontalHeaderItem(1, item)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(148, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.editID = QtWidgets.QLineEdit(self.centralwidget)
        self.editID.setGeometry(QtCore.QRect(77, 170, 61, 20))
        self.editID.setObjectName("editID")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(4, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setGeometry(QtCore.QRect(218, 170, 61, 20))
        self.editName.setObjectName("editName")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(47, 201, 51, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(107, 201, 51, 31))
        self.btnEdit.setObjectName("btnEdit")
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setGeometry(QtCore.QRect(167, 201, 51, 31))
        self.btnDel.setObjectName("btnDel")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(227, 201, 51, 31))
        self.btnExit.setObjectName("btnExit")
        subject.setCentralWidget(self.centralwidget)
        self.reload()
        self.retranslateUi(subject)
        self.btnExit.clicked.connect(subject.close)
        self.btnDel.clicked.connect(self.DELETE)
        self.btnAdd.clicked.connect(self.ADD)
        self.btnEdit.clicked.connect(self.EDIT)
        QtCore.QMetaObject.connectSlotsByName(subject)

    def retranslateUi(self, subject):
        _translate = QtCore.QCoreApplication.translate
        subject.setWindowTitle(_translate("subject", "考试科目设置"))
        item = self.tbSubject.horizontalHeaderItem(0)
        item.setText(_translate("subject", "科目编号"))
        item = self.tbSubject.horizontalHeaderItem(1)
        item.setText(_translate("subject", "科目名称"))
        self.label_3.setText(_translate("subject", "科目名称："))
        self.label_2.setText(_translate("subject", "科目编号："))
        self.btnAdd.setText(_translate("subject", "添加"))
        self.btnEdit.setText(_translate("subject", "修改"))
        self.btnDel.setText(_translate("subject", "删除"))
        self.btnExit.setText(_translate("subject", "退出"))
import rc_rc
